#!/usr/bin/env python3
"""obs-decklink-headless: bind DeckLink Output Filters to OBS scenes by name.

A small toolkit for driving headless OBS Studio on Linux with the
cg2121 "Decklink Output Filter" plugin. It solves the awkward part of a
headless setup: the filter's target device is stored as an opaque
``device_hash`` that only exists where the DeckLink hardware is, so you
cannot select it while authoring scenes on another machine.

Workflow:

  1. ``probe``   Query a running OBS instance (via obs-websocket) for the
                 DeckLink output devices and their modes, and write a
                 mapping file (scene-name -> device settings).
  2. edit        Adjust the generated mapping so each scene name maps to
                 the physical output you want.
  3. ``inject``  Read an OBS scene-collection JSON and add a bound
                 Decklink Output Filter to every scene whose name appears
                 in the mapping. Writes a ``.bak`` first.
  4. ``verify``  (optional) Read filters back live over websocket.

See the README for the full headless OBS deployment this was built for.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import uuid
from pathlib import Path

try:
    import obsws_python as obs
except ImportError:  # pragma: no cover - import guard for a clearer message
    obs = None


FILTER_ID = "decklink_output_filter"

# Human-friendly names for the OBS "mode_id" list property. This is only
# used to annotate the generated mapping; OBS is the source of truth and
# ``probe`` reads the live list, so unknown values are passed through.
COMMON_MODES = {
    -1: "Auto",
    7: "1080p30",
    9: "1080p59.94",
    10: "1080p60",
    8: "1080p50",
    16: "720p60",
}


def _require_obs() -> None:
    if obs is None:
        sys.exit(
            "obsws-python is required for this command.\n"
            "  pip install obsws-python"
        )


def _client(args):
    _require_obs()
    return obs.ReqClient(
        host=args.host, port=args.port, password=args.password, timeout=args.timeout
    )


def _first_scene_name(cl) -> str:
    scenes = cl.get_scene_list().scenes
    if not scenes:
        sys.exit("No scenes found in OBS to attach a probe input to.")
    # obs-websocket returns most-recent-first; any real scene works.
    return scenes[0]["sceneName"]


def _list_items(cl, input_name, prop):
    return cl.get_input_properties_list_property_items(input_name, prop).property_items


# --------------------------------------------------------------------------- #
# probe                                                                        #
# --------------------------------------------------------------------------- #
def cmd_probe(args) -> None:
    cl = _client(args)
    scene = _first_scene_name(cl)
    probe_name = "._decklink_probe"

    # decklink-input exposes the same device/mode enumeration as the output.
    created = False
    for kind in ("decklink-input", "decklink_input"):
        try:
            cl.create_input(scene, probe_name, kind, {}, False)
            created = True
            break
        except Exception:
            continue
    if not created:
        sys.exit(
            "Could not create a DeckLink probe input. Is the DeckLink plugin "
            "loaded and the driver running?"
        )

    try:
        devices = _list_items(cl, probe_name, "device_hash")
        devices = [d for d in devices if d.get("itemValue")]
        if not devices:
            sys.exit("OBS reports no DeckLink devices. Check driver/firmware.")

        # Pull the valid mode list once (same for all channels on a card).
        cl.set_input_settings(
            probe_name, {"device_hash": devices[0]["itemValue"]}, True
        )
        modes = _list_items(cl, probe_name, "mode_id")
    finally:
        try:
            cl.remove_input(probe_name)
        except Exception:
            pass

    default_mode = args.mode
    mapping = {
        "_comment": (
            "Generated by obs-decklink-headless probe. Edit scene names on "
            "the left to match the scene names in your OBS collection. Each "
            "scene listed here gets a DeckLink Output Filter bound to the "
            "given device_hash when you run `inject`."
        ),
        "_devices_seen": [
            {"name": d.get("itemName"), "device_hash": d.get("itemValue")}
            for d in devices
        ],
        "_modes_available": [
            {"mode_id": m.get("itemValue"), "name": m.get("itemName")} for m in modes
        ],
        "defaults": {
            "mode_id": default_mode,
            "video_connection": args.video_connection,
            "audio_connection": args.audio_connection,
            "pixel_format": args.pixel_format,
            "auto_start": True,
        },
        "scenes": {},
    }

    # Seed the scenes table: name channels io0..ioN in enumeration order.
    for idx, d in enumerate(devices):
        scene_name = f"io{idx}"
        mapping["scenes"][scene_name] = {"device_hash": d.get("itemValue")}

    out = Path(args.output)
    out.write_text(json.dumps(mapping, indent=2))
    print(f"Wrote device mapping to {out}")
    print(f"  {len(devices)} DeckLink channel(s) found:")
    for idx, d in enumerate(devices):
        print(f"    io{idx}  <-  {d.get('itemName')}  [{d.get('itemValue')}]")
    print(
        "\nEdit the 'scenes' section so the keys match your OBS scene names, "
        "then run `inject`."
    )


# --------------------------------------------------------------------------- #
# inject                                                                       #
# --------------------------------------------------------------------------- #
def _build_filter(name, settings):
    return {
        "name": f"DeckLink Out {name}",
        "uuid": str(uuid.uuid4()),
        "id": FILTER_ID,
        "versioned_id": FILTER_ID,
        "settings": settings,
        "enabled": True,
    }


def cmd_inject(args) -> None:
    mapping = json.loads(Path(args.mapping).read_text())
    defaults = mapping.get("defaults", {})
    scenes = mapping.get("scenes", {})
    if not scenes:
        sys.exit("Mapping has no 'scenes' entries. Run `probe` and edit it first.")

    collection_path = Path(args.collection)
    data = json.loads(collection_path.read_text())

    if not args.no_backup:
        shutil.copy(collection_path, str(collection_path) + ".bak")

    changed, skipped = [], []
    seen_scene_names = set()
    for src in data.get("sources", []):
        if src.get("id") != "scene":
            continue
        name = src.get("name")
        seen_scene_names.add(name)
        if name not in scenes:
            continue

        settings = dict(defaults)
        settings.update(scenes[name])  # per-scene overrides win
        if "device_hash" not in settings:
            skipped.append((name, "no device_hash"))
            continue

        filters = src.setdefault("filters", [])
        # idempotent: drop any prior filter of this id before re-adding
        filters[:] = [f for f in filters if f.get("id") != FILTER_ID]
        filters.append(_build_filter(name, settings))
        changed.append(name)

    collection_path.write_text(json.dumps(data, indent=4))

    for name in changed:
        print(f"  bound filter -> scene '{name}'")
    for name, why in skipped:
        print(f"  skipped '{name}': {why}")

    missing = [s for s in scenes if s not in seen_scene_names and not s.startswith("_")]
    for name in missing:
        print(f"  WARNING: mapping scene '{name}' not found in collection")

    if not changed:
        print("No scenes were modified. Do the mapping keys match scene names?")
    else:
        print(f"\nUpdated {collection_path}")
        if not args.no_backup:
            print(f"Backup: {collection_path}.bak")
        print("Restart OBS (or reload the scene collection) to apply.")


# --------------------------------------------------------------------------- #
# verify                                                                       #
# --------------------------------------------------------------------------- #
def cmd_verify(args) -> None:
    cl = _client(args)
    scenes = cl.get_scene_list().scenes
    found = 0
    for s in scenes:
        name = s["sceneName"]
        try:
            filters = cl.get_source_filter_list(name).filters
        except Exception:
            continue
        for f in filters:
            if f.get("filterKind") == FILTER_ID:
                found += 1
                dh = f.get("filterSettings", {}).get("device_hash", "?")
                state = "enabled" if f.get("filterEnabled") else "disabled"
                print(f"  {name}: {f.get('filterName')} -> {dh} ({state})")
    if not found:
        print("No DeckLink Output Filters are currently live.")


# --------------------------------------------------------------------------- #
# arg parsing                                                                  #
# --------------------------------------------------------------------------- #
def _add_ws_args(p):
    p.add_argument("--host", default="127.0.0.1", help="obs-websocket host")
    p.add_argument("--port", type=int, default=4455, help="obs-websocket port")
    p.add_argument(
        "--password",
        default=None,
        help="obs-websocket password (or set OBS_WS_PASSWORD)",
    )
    p.add_argument("--timeout", type=float, default=5.0, help="request timeout (s)")


def _resolve_password(args):
    import os

    if getattr(args, "password", None) is None:
        args.password = os.environ.get("OBS_WS_PASSWORD")
    if args.password is None and args.command in ("probe", "verify"):
        sys.exit(
            "An obs-websocket password is required. Pass --password or set "
            "OBS_WS_PASSWORD."
        )


def build_parser():
    p = argparse.ArgumentParser(
        prog="obs-decklink-headless",
        description="Bind DeckLink Output Filters to OBS scenes by name, headlessly.",
    )
    sub = p.add_subparsers(dest="command", required=True)

    pp = sub.add_parser("probe", help="discover DeckLink devices -> mapping file")
    _add_ws_args(pp)
    pp.add_argument("-o", "--output", default="decklink-map.json")
    pp.add_argument("--mode", type=int, default=10, help="default mode_id (10=1080p60)")
    pp.add_argument("--video-connection", type=int, default=1, help="1=SDI")
    pp.add_argument("--audio-connection", type=int, default=1, help="1=Embedded")
    pp.add_argument(
        "--pixel-format", type=int, default=846624121, help="846624121=8-bit YUV"
    )
    pp.set_defaults(func=cmd_probe)

    pi = sub.add_parser("inject", help="add bound filters to a scene collection")
    pi.add_argument("collection", help="path to the OBS scene-collection JSON")
    pi.add_argument("-m", "--mapping", default="decklink-map.json")
    pi.add_argument("--no-backup", action="store_true")
    pi.set_defaults(func=cmd_inject)

    pv = sub.add_parser("verify", help="list live DeckLink filters over websocket")
    _add_ws_args(pv)
    pv.set_defaults(func=cmd_verify)

    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    _resolve_password(args)
    args.func(args)


if __name__ == "__main__":
    main()
